version: "2"

formatters:
  enable:
    - gofumpt
    - golines

  settings:
    gofumpt:
      module-path: agentlab
      extra-rules: true
    golines:
      max-len: 120

linters:
  default: none

  enable:
    - lll

  settings:
    lll:
      line-length: 120
